apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trusted-marketplace-portal
  name: trusted-marketplace-portal
spec:
  selector:
    matchLabels:
      app: trusted-marketplace-portal
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trusted-marketplace-portal
    spec:
      volumes:
      - name: ishare-keys
        secret:
          secretName: ishare-keys
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - env:
        - name: PROVIDER_CLIENT_ID
          value: "-PROVIDER_ID-"
        - name: CONSUMER_CLIENT_ID
          value: "-CONSUMER_ID-"
        - name: PROVIDER_CLIENT_ID_M2M
          value: "-PROVIDER_ID_M2M-"
        - name: CONSUMER_CLIENT_ID_M2M
          value: "-CONSUMER_ID_M2M-"
        - name: CONSUMER_EMAIL
          value: "-EMAIL-"
        - name: KEYROCK_URL
          value: "https://accounts.odala.stag.profirator.fi"
        - name: KEYROCK_URL_M2M
          value: "https://accounts.-DOMAIN-"
        - name: APP_URL
          value: "https://trusted-marketplace-portal.-DOMAIN-"
        - name: SCORPIO_URL
          value: "https://kong.-DOMAIN-"
        - name: PRIVATE_KEY_FILE
          value: private_key
        - name: X5C_VALUE_FILE
          value: x5c
        image: IMAGE
        imagePullPolicy: Always
        volumeMounts:
        - name: ishare-keys
          mountPath: "/keys/secrets/"
        name: trusted-marketplace-portal
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: trusted-marketplace-portal
  name: trusted-marketplace-portal
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: trusted-marketplace-portal
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Referrer-Policy 'same-origin';
      add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline';";
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAuditEngine On
      #SecAuditLog /dev/stdout
      SecAuditLogFormat JSON
      SecAction "id:900001, phase:1, nolog, pass, t:none, setvar:tx.paranoia_level=1, setvar:tx.allowed_methods=GET POST"

  name: trusted-marketplace-portal
spec:
  rules:
  - host: trusted-marketplace-portal.-DOMAIN-
    http:
      paths:
      - backend:
          service:
            name: trusted-marketplace-portal
            port:
              number: 5000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - trusted-marketplace-portal.-DOMAIN-
    secretName: trusted-marketplace-portal-cert
